<?php

return [
    [
        "title"            => "Spotify Web",
        "author"           => "Gary Alvarez",
        "creation_date"    => "2023-03-22",
        "last_update"      => "2023-03-27",
        "collaborators"    => "",
        "description"      => "A clone of Spotify Web",
        "languages"        => "HTML, CSS",
        "link_github"      => "https://github.com/GarySmithAlvarezVenturo/html-css-spotifyweb",
    ],
    [
        "title"            => "Campominato",
        "author"           => "Gary Alvarez",
        "creation_date"    => "2023-04-06",
        "last_update"      => "2023-05-01",
        "collaborators"    => "",
        "description"      => "A clone of Minefield",
        "languages"        => "HTML, CSS, JS ",
        "link_github"      => "https://github.com/GarySmithAlvarezVenturo/js-campominato-dom",
    ],
    [
        "title"            => "Social Post",
        "author"           => "Gary Alvarez",
        "creation_date"    => "2023-05-03",
        "last_update"      => "2023-05-03",
        "collaborators"    => "",
        "description"      => "A clone of Facebook",
        "languages"        => "HTML, CSS, JS",
        "link_github"      => "https://github.com/GarySmithAlvarezVenturo/js-social-posts",
    ],
    [
        "title"            => "BoolzApp",
        "author"           => "Gary Alvarez",
        "creation_date"    => "2023-05-10",
        "last_update"      => "2023-06-06",
        "collaborators"    => "",
        "description"      => "A clone of WhatsApp",
        "languages"        => "HTML, CSS, JS",
        "link_github"      => "https://github.com/GarySmithAlvarezVenturo/vue-boolzapp",
    ],
    [
        "title"            => "BoolFlix",
        "author"           => "Gary Alvarez",
        "creation_date"    => "2023-05-24",
        "last_update"      => "2023-06-26",
        "collaborators"    => "",
        "description"      => "A clone of Nelflix",
        "languages"        => "HTML, JS, VUE",
        "link_github"      => "https://github.com/GarySmithAlvarezVenturo/vite-boolflix",
    ],
    [
        "title"            => "Project Html-VueJs",
        "author"           => "Gary Alvarez",
        "creation_date"    => "2023-05-29",
        "last_update"      => "2023-06-05",
        "collaborators"    => "",
        "description"      => "A clone of a Website",
        "languages"        => "HTML, VUE",
        "link_github"      => "https://github.com/DavideFarci/proj-html-vuejs.git",
    ],
    [
        "title"            => "DC Comics",
        "author"           => "Gary Alvarez",
        "creation_date"    => "2023-06-29",
        "last_update"      => "2023-07-03",
        "collaborators"    => "",
        "description"      => "A clone of a Website of DC Comics",
        "languages"        => "PHP, BLADE",
        "link_github"      => "https://github.com/GarySmithAlvarezVenturo/laravel-dc-comics",
    ],
    [
        "title"            => "Laravel Boolean",
        "author"           => "Paolo Falco",
        "creation_date"    => "2023-07-04",
        "last_update"      => "2023-07-004",
        "collaborators"    => "Alessandra Casu,Gary Alvarez,Antonio Nicolaci",
        "description"      => "A invoices organizer",
        "languages"        => "PHP, BLADE, JS",
        "link_github"      => "https://github.com/GarySmithAlvarezVenturo/laravel-boolean",
    ],
];